credentials:
  usernames:
    admin:
      name: Administrateur
      password: MonMotDePasse2025
cookie:
  expiry_days: 30
  key: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
  name: postetunisienne_auth
preauthorized:
  emails:
    - admin@example.com